name: Deploy ASP.NET

on:
  push:
    branches:
      - main  # O workflow será executado quando houver push na branch 'main'

jobs:
  build:
    runs-on: windows-latest  # Altere de ubuntu-latest para windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # Versão correta do .NET

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./pap

      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: ./pap

      - name: Publish
        run: dotnet publish -c Release -o ./output
        working-directory: ./pap

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./pap/output
